### ISSUE TITLE
Request: Purge command

### ISSUE THREAD

**Issue by BluSunrize** [artdude543/BeepBot-Feedback#3]
Just a way to remove stuff said by a certain user? =)

**Comment by artdude543** [comment]
Will add in the next update :)

**Comment by artdude543** [comment]
This has been added in version `2.0.0-9`, which will be pushed later today at some point.

**Comment by BluSunrize** [comment]
\o/

**Comment by artdude543** [comment]
This is now pushed and live on the bot :) 

- Just as a small note their is a small bug on the Beam API (Hopefully being fixed soon) So is the command responds with nothing, it's the bot handling errors silently for now till the bug is fixed.
